image: docker:stable

options:
  docker: true

pipelines:
  custom: #branches: To auto run based on branch push
    develop:
      - step:
          name: Test only
          script:
              # Install dependencies
              - ./ci/dependencies.sh
              # Build both Node.js and angular projects
              - ./build.sh
              # Check our build
              - docker-compose up -d --build
              - docker-compose logs
              - docker-compose down
              # Run redis server on local to run test
              - redis-server --daemonize yes
              # Run tests
              - npm run test
    master:
      - step:
          name: Test and Deploy to S3
          deployment: production
          script:
              # Install dependencies
              - ./ci/dependencies.sh
              # Build both Node.js and angular projects
              - ./build.sh
              # Check our build
              - docker-compose up -d --build
              - docker-compose logs
              - docker-compose down
              # Run redis server on local to run test
              - redis-server --daemonize yes
              # Run tests
              - npm run test
              # Preparation of deployement based on the actual build
              # [i choosed use zip to compress relevant files for deployement]
              - ./ci/before_deploy.sh
              # Deploy to AWS S3 
              - pipe: atlassian/aws-s3-deploy:0.2.4
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: $PRODUCTION_BUCKET_NAME
                  ACL: "public-read"
                  LOCAL_PATH: "./deploy"