version: '3'

services:
    redis:
        image: sickp/alpine-redis:4.0.8
        networks: 
          - webnet

    node-angular:
        build: ./
        image: node-angular:${BITBUCKET_COMMIT}
        networks: 
            - webnet
        ports:
            - "3000:3000"
        environment:
            PORT : 3000
            REDIS_STRING : redis://redis
            SERVER_TIMEOUT : 3000
        volumes:
          - ./data:/data
        depends_on:
            - redis

networks:
    webnet: